### ISSUE TITLE
[STUPID] Where do I put these libs?

### ISSUE THREAD

**Issue by Ianmcmill** [evil-mad/plotink#11]
Where do I put these libraries?
Into Inkscape User Extensions?

**Comment by oskay** [comment]
That depends a good deal on what you are trying to do.

Calling it or me stupid really isn't going to solve any problems.

**Comment by Ianmcmill** [comment]
I refered stupid to me. Stupid in the sense of an obviously "stupid" question.
This is the characteristics of [] infront of topics on the internet I thougt. 
Sorry?!

**Comment by Ianmcmill** [comment]
I just wanted to point out again that I didn't want to insult anyone but me...
