### ISSUE TITLE
Restructure to avoid direct error reporting

### ISSUE THREAD

**Issue by oskay** [evil-mad/plotink#21]
`ebb_serial.query` and `ebb_serial.command` both have `inkex.errormsg` calls that directly print error messages.

Those, in turn are called widely in the various functions in ebb_motion.

For handling a wider variety of use cases, we need to revise these functions so that they no longer directly print error messages.

Possible solutions:
(1) Modify these functions (and those that call them) to return an error message.

(2) Add the functions to a class, such that the error status can be added to a string variable in that class, something along the lines of `ebb_serial.error_msg`, that can be accessed by scripts that import ebb_serial.

**Comment by oskay** [comment]
@shoshber Can you please tell me what you think?

**Comment by shoshber** [comment]
It's a great idea. I can jump right on this if you like. The quickest good solution is to convert calls to `inkex.errormsg` into python exceptions (https://docs.python.org/3/tutorial/errors.html). Callers can then either ignore the exceptions or catch them and handle them (e.g.,  quit, log the message, log the message and continue, etc.).

This also might be a good time to introduce a logging methodology to the axidraw suite (using the `logging` module, for example). Some discussion: (https://softwareengineering.stackexchange.com/questions/37294/logging-why-and-what)

**Comment by oskay** [comment]
Moving to errors does sound like a reasonable approach. We do need to keep in mind that some additional software besides the AxiDraw does use this package.

**Comment by shoshber** [comment]
Software under our control, or external consumers? We should definitely increase the version number either way.

**Comment by oskay** [comment]
I think that we only need to worry about 
https://github.com/evil-mad/EggBot and https://github.com/evil-mad/wcb-ink

Both of these are due for updates. I've been considering forking the AxiDraw software to make new versions of these. Alternately, perhaps, it would be better to "commodify" the AxiDraw software core so that AxiDraw and the others are wrappers around it.

**Comment by shoshber** [comment]
If I understand you correctly, the commodify option is what I would pick. Something else to talk about on our phone call next week.

**Comment by oskay** [comment]
Sure. This is not necessarily something that we need to do in the near term; I'm happy to continue updating those other projects as we go along in the near future.

**Comment by shoshber** [comment]
https://github.com/evil-mad/plotink/pull/23
