### ISSUE TITLE
How to make a pancake printer into an inkscape extension

### ISSUE THREAD

**Issue by amyolivyade** [evil-mad/plotink#52]
I see that you have provided a lot of inkscape extension files. Thank you very much for your help! But I had a problem. I'm currently using a pancake printer called pancakebot, and I want to make it into an inkscape extension file, I need to extend the function of the plugin, don't need many layers, just need it to draw the line path! 
I'm not a programmer, so I talked to programmers around me, and they all said it's hard, they can't make it, I don't know if you can make it, but if you can, you're awesome! You can be the teacher of many programmers!!

This link is the software information for the pancake printer, which is open source.

https://github.com/pancakebot

**Comment by oskay** [comment]
Yes, I saw your post over on the Inkscape forum.

This project, plotink, contains some helper routines for some specific pen plotters. So far as I know, none of the code that it uses or generates is compatible with the pancakebot.

It looks like the pancakebot uses gcode for control. You can already use the Inkscape g-code tools extensions to generate g-code that the pancakebot can run. This doesn't require any new software to be written for you.

**Comment by amyolivyade** [comment]
Thank you very much for your answer ，Can you tell me where I can find the Gcode extension? I found an extension like this earlier, but when I opened it up it was an extension of the Pen Robot, and some of the instructions were different

**Comment by oskay** [comment]
No, this isn't something that we can help you with.  However, the G code tools extensions that I was referring to are these: https://github.com/cnc-club/gcodetools  

They are not the only ones out there. However, we do not use any of these tools, so we do not know much about them.
